spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway-zuul

server:
  port: 8765

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  routes:
    user-management-service: /user-management-service/**
    authorization-server:
      sensitiveHeaders: Authorization
      path: /authorization-server/**
      stripPrefix: false
  add-proxy-headers: true

security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://localhost:8085/authorization-server/oauth/token
      userAuthorizationUri: /authorization-server/oauth/authorize
      clientId: fooClient
      clientSecret: fooSecret
    resource:
      jwt:
        keyValue: "abc"
      id: fooScope
      serviceId: ${PREFIX:}resource

#logging:
#  level.org.springframework.security: DEBUG

