spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway-zuul

server:
  port: 8765

#ribbon:
#  eureka:
#    enabled: false

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
zuul:
  routes:
    user-management-service: /user-management-service/**
    authorization-server:
      sensitiveHeaders: Authorization
      path: /authorization-server/**
      stripPrefix: false
  add-proxy-headers: true
  host:
    connect-timeout-millis: 121000 # starting the connection
    socket-timeout-millis: 121000
  ribon:
    eureka:
      enabled: false
    ConnectTimeout: 60000
    ReadTimeout: 60000
security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://localhost:8085/authorization-server/oauth/token
      userAuthorizationUri: /authorization-server/oauth/authorize
      clientId: fooClient
      clientSecret: fooSecret
    resource:
      jwt:
        keyValue: "abc"
      id: fooScope
      serviceId: ${PREFIX:}resource

#logging:
#  level.org.springframework.security: DEBUG

